### ISSUE TITLE
connection to speedtest failing

### ISSUE THREAD

**Issue by TRingo1** [raaaimund/internet-speed-monitor#2]
speedtest.net has changed cli connection, and failing, is there a solution to correct this error?

> #Error for speedtest.net
crond: USER root pid  12 cmd /usr/local/bin/speedtest --accept-license -s 5025 -f json > $(mktemp -u -p /var/log/speedtest XXXXXX).json
speedtester_1  | [2021-04-20 13:15:06.201] [error] Configuration - SSL connect error (UnknownException)
speedtester_1  | [2021-04-20 13:15:06.201] [error] Configuration - Cannot retrieve configuration document (0)
speedtester_1  | [2021-04-20 13:15:06.202] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)
speedtester_1  | [2021-04-20 13:15:06.202] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)
speedtester_1  | {"type":"log","timestamp":"2021-04-20T13:15:06Z","message":"Configuration - Could not retrieve or read configuration (ConfigurationError)","level":"error"}

**Comment by raaaimund** [comment]
Hi @TRingo1. I added the ``--accept-gdpr`` argument. At least that was a problem on my side for getting results from the speedtest cli. Now I am able to retrieve results again. But on your side, maybe your container has no access to the internet? Try to connect to your container and ping some site on the web (e.g. 8.8.8.8).
