### ISSUE TITLE
Adding documentation on arm/amd64 usage

### ISSUE THREAD

**Issue by georg90** [raaaimund/internet-speed-monitor#4]
Nice project!

Maybe adding a tag that we have fixed values for cpu architecture might help others to start faster

e.g. `armhf` in the following lines needs to be changed to `amd64` on x86 host systems
https://github.com/raaaimund/internet-speed-monitor/blob/master/telegraf/Dockerfile#L4-L6

**Comment by raaaimund** [comment]
Thanks a lot @georg90 for mentioning this, I will fix the issue with the architecture.
